# permissions to do edit builders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builder-editor-role
rules:
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - builders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - builders/status
  verbs:
  - get
  - patch
  - update
