# permissions to do viewer builders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builder-viewer-role
rules:
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - builders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - builders/status
  verbs:
  - get
