# permissions to do edit devenvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devenv-editor-role
rules:
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - devenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - devenvs/status
  verbs:
  - get
  - patch
  - update
