# permissions to do viewer devenvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devenv-viewer-role
rules:
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - devenvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - c-n-d-e.kube-platform.dev
  resources:
  - devenvs/status
  verbs:
  - get
