namespace: trainer

resources:
- init-container-test2.yaml
- rbac.yaml

secretGenerator:
- name: docker-credentials
  files:
    - .dockerconfigjson

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true